### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by DEVCODENET** [Nandakishanr/SampleTest#1]
Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/base.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_resources_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/lib/arm64, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/base.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.example.manvish.sampletest-jMVvOv1UzqIU44Uta-jXEQ==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libNativeMorphoSmartSDK_6.13.2.0-4.1.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1657)
       at com.morpho.morphosmart.sdk.MorphoDeviceNative.<clinit>(MorphoDevice.java:1320)
       at com.morpho.morphosmart.sdk.MorphoDevice.<clinit>(MorphoDevice.java:22)
       at com.manvish.sampletest.Activities.SensorInitializationClass.initializeDevice(SensorInitializationClass.java:61)
       at com.manvish.sampletest.Utils.CommanUtils.initializeSensor(CommanUtils.java:172)
       at com.manvish.sampletest.Activities.MainActivity.onCreate(MainActivity.java:141)
       at android.app.Activity.performCreate(Activity.java:7183)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6940)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by PriyankaAlachiya** [comment]
Please suggest solution

**Comment by iamkdblue** [comment]
@PriyankaAlachiya and @DEVCODENET did you get any solution for this error ?

**Comment by nickssilver** [comment]
Hello there, if you still have a problem on this i got the needed library and willing to share with you
